import { ClaudeModelInfo } from '../types';

export const CLAUDE_MODELS: ClaudeModelInfo[] = [
  {
    id: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    tier: 'Mythos Tier (Supreme Flagship)',
    thinkingLevel: 'Level 5 — Supreme & Deepest Thinking',
    reasoningPower: '100% (Pinnacle Benchmark — Top & Best)',
    speed: 'High-Velocity Mythos Engine',
    tagline: 'Anthropic’s pinnacle flagship: Top intelligence & supreme reasoning',
    description: 'The absolute pinnacle of Anthropic’s Claude 5 family. Sits above Claude Opus in capability with supreme reasoning, dual-use safety measures, autonomous code engineering, and unprecedented problem-solving.',
    badge: '★ TOP & BEST',
    accent: '#D97757',
  },
  {
    id: 'claude-mythos-5-1',
    name: 'Claude Mythos 5.1',
    tier: 'Mythos Tier (Enterprise Core)',
    thinkingLevel: 'Level 5 — Frontier Systems Deliberation',
    reasoningPower: '98% (Enterprise Frontier)',
    speed: 'High-Velocity Mythos Engine',
    tagline: 'Unrestricted Mythos-tier flagship for enterprise & scientific compute',
    description: 'Shares the underlying Mythos-tier architecture with Fable 5.1, dedicated to mission-critical infrastructure, massive scientific data synthesis, and advanced organizational workflows.',
    badge: 'Enterprise',
    accent: '#C25E3E',
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    tier: 'Opus Tier (Deep Thinker)',
    thinkingLevel: 'Level 4 — Exhaustive Analytical Deliberation',
    reasoningPower: '92% (Deep Thought & Philosophy)',
    speed: 'Measured Deliberative Pace',
    tagline: 'Deep analytical deliberation, research synthesis & literature',
    description: 'Anthropic’s premier model for nuanced writing, profound philosophy, scholarly research, creative literature, and exhaustive multi-step problem solving.',
    badge: 'Deep Thinker',
    accent: '#8B5CF6',
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    tier: 'Sonnet Tier (Workhorse)',
    thinkingLevel: 'Level 3 — Adaptive Dynamic Reasoning',
    reasoningPower: '85% (High-Efficiency Execution)',
    speed: 'Fast Execution',
    tagline: 'Ideal balance of high intelligence and execution speed',
    description: 'The everyday workhorse for rapid full-stack programming, complex agentic workflows, data pipelines, and general productivity.',
    badge: 'Popular',
    accent: '#3B82F6',
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    tier: 'Haiku Tier (Ultra-Fast)',
    thinkingLevel: 'Level 2 — Instantaneous Low-Latency',
    reasoningPower: '74% (Agile Low-Latency)',
    speed: 'Ultra-Fast (Instantaneous)',
    tagline: 'Instant throughput and rapid execution for agile queries',
    description: 'Anthropic’s fastest model designed for lightweight, high-volume tasks, quick drafts, data parsing, and instant real-time interactions with zero lag.',
    badge: 'Fastest',
    accent: '#10B981',
  },
];
